@TM:1392727885
@W:  :"":0:0:0:-1|Ignoring top level module 'assignment4.liaison' as specified in project file
@N:  :"":0:0:0:-1|Running in logic synthesis mode without enhanced optimization
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@TM:1392730174
@N: FX271 :"":0:0:0:-1|Instance "status_internal_or_0_0[0]" with 2 loads has been replicated 1 time(s) to improve timing 
@TM:1392727885
@W: FX474 :"":0:0:0:-1|User specified initial value found in some of the sequential elements in the design. Applying an initial value to a register may not deliver the best synthesis results. For example, registers with initial values may be preserved and retiming/pipelining may not be performed. To improve synthesis results you may want to remove the register initialization from the RTL code 
@N: FX493 :"":0:0:0:-1|Applying Initial value "000" on instance: last_status[2:0] 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF276 :"":0:0:0:-1|Gated clock conversion enabled, but no gated clocks found in design 
@TM:1392730174
@N: MF322 :"":0:0:0:-1|Retiming summary: 1 registers retimed to 3 
@TM:1392727885
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1392727883
@N: CD720 :"C:\Program Files (x86)\Synplicity\fpga_C200906\lib\vhd\std.vhd":123:18:123:21|M
@N: CD630 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":37:7:37:13|M
@W: CL117 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":117:4:117:7|M
@TM:1392730174
@N: FX271 :"c:\users\student\documents\github\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":170:3:173:19|M
@TM:1392727883
@W: CL117 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":180:1:180:2|M
@TM:1392729919
@N: FX271 :"c:\users\student\documents\github\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":180:1:180:2|M
@TM:1392727885
@W: MO129 :"c:\users\student\documents\github\mod-anal-dig-sys\ex4\assignment4\src\liaison.vhd":180:1:180:2|M
