@TM:1393229396
@W:  :"":0:0:0:-1|Ignoring top level module 'ex5.ex511' as specified in project file
@N:  :"":0:0:0:-1|Running in logic synthesis mode without enhanced optimization
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF276 :"":0:0:0:-1|Gated clock conversion enabled, but no gated clocks found in design 
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1393229395
@N: CD720 :"C:\Program Files (x86)\Synplicity\fpga_C200906\lib\vhd\std.vhd":123:18:123:21|M
@N: CD630 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex5\src\ex5-1-1.vhd":4:7:4:11|M
@W: CL159 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex5\src\ex5-1-1.vhd":6:3:6:7|M
@W: CL111 :"C:\Users\Student\Documents\GitHub\mod-anal-dig-sys\ex5\src\ex5-1-1.vhd":16:2:16:3|M
